Repository CA-G12/mostafa-nada-autoComplete, pull requests merged in 2022-08, with the labels that each got.

#2 create file stcruture contains public folder with css and html files …
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/css/details.css
  public/css/index.css
  public/details.html
  public/details.js
  public/image/pngaaa.com-1539664 (1).png
  public/index.html
  public/script.js
  src/fetch.js
  src/movies.json
  src/router.js
  src/server.js
  test.test.js
Labels: approved

#4 create movies json file
  src/movies.json
Labels: approved

#9 create server file
  src/router.js
  src/server.js
Labels: in progress

#10 create index
  public/index.html
Labels: awaiting-review

#15 13 styling home page
  public/css/index.css
  public/image/pngaaa.com-1539664 (1).png
  public/image/spy_carousel.png
  public/index.html
Labels: awaiting-review

#16 12 endpoints
  public/script.js
  src/router.js
  src/server.js
Labels: approved

#17 create function auto complete
  public/script.js
  src/router.js
Labels: approved

#19 create details show relates #18
  public/css/index.css
  public/index.html
  public/script.js
  src/router.js
Labels: approved

#21 fix rating
  public/script.js
Labels: approved

#28 24 styling details section
  package.json
  public/css/index.css
  public/details.html
  public/details.js
  public/index.html
  public/script.js
Labels: awaiting-review
